// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConfettiController from "./confetti_controller"
application.register("confetti", ConfettiController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import DeliveryChannelController from "./delivery_channel_controller"
application.register("delivery-channel", DeliveryChannelController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import SelectionController from "./selection_controller"
application.register("selection", SelectionController)
